первая версия удаления ссылки
jon69/shorturl pull request #14
Opened 2023-02-22 16:50 UTC by jon69

2023-02-24 18:36 UTC, lugingf requested changes
Оставил комментарии.
Плюс, я не вижу, чтобы тут было асинхронное удаление, была использована многопоточность

2023-02-24 18:36 UTC, lugingf commented on internal/app/db/dbhandler.go
> +	db, errOpen := sql.Open("postgres", conn)
Мне кажется что sql.Open надо делать только один раз и класть это в структурку как зависимость. На каждый запрос открывать коннект - это не дело

2023-02-24 18:36 UTC, lugingf commented on internal/app/db/dbhandler.go
>  	db, errOpen := sql.Open("postgres", conn)
Странно что я раньше этого не заметил

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
> +	user := "1"
Это что у нас такое?

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
> +		log.Print("err DelUserURL can not find uid=" + uid + " strKey=" + strKey)
Давай так логи не писать. Если хотим что-то вставить, то давай использовать fmt.Sprintf()

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
> +	entry, ok2 := h.urls[user][key]
Если вводим второй ok, я бы предложил из оба как-то обозвать, а то выглядит как костыли

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
>  	if h.connDB != "" {
Давай и тут и с file инвертируем условие, и уберем else, чтобы код так не уплывал с отступами.

И зачем нам вообще эти проверки? Мы по идее не должны работать вообще, если у нас нет коннекта к БД при условии что сервис его ожидает. То есть эта проверка должна быть где-то в main и до вызова метода мы не должны доходить вообще, если что-то не то с коннектом

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
> +		log.Print("can not json.marshal")
Может нам тут уже выйти с ошибкой надо?

2023-02-24 18:36 UTC, lugingf commented on internal/app/storage/storage.go
> +		if err == nil {
обычно 
```
if err != nil {
пишем ошибку, выходим с ошибкой
}
дальше код нормальной работы
```

2023-03-01 19:39 UTC, jon69 commented on internal/app/db/dbhandler.go
> +	db, errOpen := sql.Open("postgres", conn)
а что если посгрес упал а потом поднялся, то подключение уже будет не валидным. Надо заново делать open.
Зачем держать соединение, если нет запросов. Тут если делать по уму, много чего можно придумать

2023-03-01 19:41 UTC, jon69 commented on internal/app/storage/storage.go
> +	user := "1"
а это всему виной плохое объяснение задания в инкременте. Сначала делаешь то, что там написано, потом делаешь комиты, видишь что тесты не работают, потому что задание и тесты совершенно различаются и потом уже подгоняешь под тесты

2023-03-01 19:41 UTC, jon69 commented on internal/app/storage/storage.go
> +		log.Print("err DelUserURL can not find uid=" + uid + " strKey=" + strKey)
Почему так не надо писать?

2023-03-01 19:43 UTC, jon69 commented on internal/app/storage/storage.go
>  	if h.connDB != "" {
Если нет коннекта к БД то мы должны все еще уметь работать либо с файлом либо с оперативной памятью.

2023-03-01 19:44 UTC, jon69 commented on internal/app/storage/storage.go
> +		if err == nil {
на вкус и цвет все фломастеры разные )

2023-03-01 19:45 UTC, jon69 commented on internal/app/storage/storage.go
> +		log.Print("can not json.marshal")
тесты прошли вроде как

2023-03-03 16:53 UTC, lugingf commented on internal/app/storage/storage.go
> +		log.Print("err DelUserURL can not find uid=" + uid + " strKey=" + strKey)
Строки в Go немутабельны, это значит что на каждую конкатенацию создается новый объект, что замедляет процесс
Внутри fmt под капотом эти операции оптимизированы на уровне рун, кажется.

2023-03-03 16:58 UTC, lugingf commented on internal/app/storage/storage.go
>  	if h.connDB != "" {
Это обычно не решается так. Если задача делать бекап для случая упавшей БД, то делается какой-нибудь общий процесс failover, который или делает дамп или сохраняет в кэш. Например, пишется какой-нибудь декоратор в виде обертки над структурой, который выполняет свою логику. Но решать такое if'чиками - моветон

В общем случае, если у тебя нестабильная БД и ты иногда то в файл пишешь, то в БД, то у тебя получается неконсистентные данные в БД. 

Обычно падение БД - это очень критичный кейс, и падение сервиса в этом случае вполне допустимое явление, если нет какого-то установленного failover процесса

2023-03-03 16:58 UTC, lugingf commented on internal/app/storage/storage.go
> +		log.Print("can not json.marshal")
Тут вопрос не в тестах, а в логике работы сервиса. Если ты не смог смаршалить сообщение, то кажется надо прерывать операцию на этом месте

2023-03-03 17:01 UTC, lugingf commented on internal/app/storage/storage.go
> +		if err == nil {
Лишние отступы обычно мешают чтению кода. Если есть возможность сделать убрать отступ - стоит так и сделать.
РАвно как и если есть возможность написать if без использования else - то тоже.

Предлагаю почитать "Рефакторинг" Фаулера

2023-03-03 17:01 UTC, lugingf approved these changes

2023-06-03 11:57 UTC, merged